/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <system_stm32f4xx.h>
#include <timer.h>
#include <Ucglib.h>

static ucg_t ucg;
int main(void)
{
	SystemCoreClockUpdate();
	TimerInit();
	Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	ucg_ClearScreen(&ucg);

	ucg_SetFont(&ucg, ucg_font_helvB08_tf);
	ucg_SetColor(&ucg, 0, 14, 212, 173);
	ucg_SetColor(&ucg, 1, 0, 0, 0);
	ucg_SetRotate180(&ucg);
	ucg_DrawString(&ucg, 0, 12, 0, "I love Embedded");
	ucg_DrawString(&ucg, 0, 26, 0, "Programing");

    /* Loop forever */
	while(1){
		processTimerScheduler();
	}
}
